objective:
  - reconstruction_objective

dataset:
  - radio_interferometry:
      fits_name : "m1_n.fits"
      image_size: 1024
      noise_level: 0.1
      simulator_hash: # Required. If null, dataset lists available hashes.

solver:
  - PnP:
      denoiser: drunet
      denoiser_sigma: 0.1
      distribute_physics: False
      distribute_denoiser: False
      init_method: 'pseudo_inverse'
      step_size_scale: 0.9
      
